package utils.c;

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


class libJindex_newJNI {
  public final static native String getMimeType(String jarg1);
  public final static native String getIconFromMimeType(String jarg1);
}
