/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.28
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package utils.c;

public class libJIndex_new {
  public static native String  getMimeType(String filename);
  public static native String getIconFromMimeType(String filename);
}
