package utils.c;


/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.29
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class libJindex_new {
  public static String getMimeType(String filename) {
    return libJindex_newJNI.getMimeType(filename);
  }

  public static String getIconFromMimeType(String filename) {
    return libJindex_newJNI.getIconFromMimeType(filename);
  }

}
