/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class utils_c_libJIndex_new */

#ifndef _Included_utils_c_libJIndex_new
#define _Included_utils_c_libJIndex_new
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     utils_c_libJIndex_new
 * Method:    getMimeType
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_utils_c_libJIndex_new_getMimeType
  (JNIEnv *, jclass, jstring);

/*
 * Class:     utils_c_libJIndex_new
 * Method:    getIconFromMimeType
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_utils_c_libJIndex_new_getIconFromMimeType
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
